### ISSUE TITLE
Add option to load config from file

### ISSUE THREAD

**Issue by mszostok** [mszostok/version#13]
**Description**

Add option to load config from file. Support both YAML and JSON files (detects dynamically). Configure options:

1. Enable loading style from environment variable via `version.WithPrettyStyleFromEnv("ENV_NAME_FOR_FILE_PATH")`,
2. Load a style file directly using Go function, `version.WithPrettyStyleFile`.

**Reasons**

It enables dynamic styling without the need to know/use Go.

**Comment by Kamsiy** [comment]
is this available to pick up?

**Comment by mszostok** [comment]
Hi, yes, 

IMO we can also support only YAML in the first stage. Later we can "port" [`NewYAMLOrJSONDecoder`](https://github.com/kubernetes/apimachinery/blob/cc480d32965030b066c940e2a406cc647d3242f4/pkg/util/yaml/decoder.go#L263-L267) :)

for loading the style configuration, you can take a look on https://github.com/charmbracelet/glamour#styles as they do exactly this :)

**Comment by Kamsiy** [comment]
sounds good, I'll take a look, sorry for the late responses
